---
# tasks file for roles/update_os
- name: clean yum cache
  command: yum clean all
- name: upgrade all packages
  yum: name='*' disablerepo="*" enablerepo="*-NTT" state=latest #bugfix=yes and secusrity=yes
  async: 7200 # wait for this task 120 mins 
#  poll: 1
  poll: 0
  register: yum_update
#  command: yum -y update
- name: check the upgrade task
  async_status: jid={{ yum_update.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 120
  delay: 60 #check the status every 1 mins 
- name: restore NTT repo
  include_role: name=ntt_local_repo
