---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    provider:
      server: 10.10.14.86
      validate_certs: no
      server_port: 443

  roles:
    - new_pool
   # - new_member
   # - new_VS
