---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:
  - name: verify centos6 boot files existing
    stat: path: "/boot/{{ item }}"
    with_items:
      - "{{ centos6_boot_file }}"
    failed_when: item.stat.exists == false
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
  - name: verify centos7 boot files existing
    stat: path: "/boot/{{ item }}"
    with_items:
      - "{{ centos7_boot_file }}"
    failed_when: item.stat.exists == false
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
  - name: notify reboot
    notify:
    - record time after run playbook
  handlers:
  - name: record time after run playbook
    shell: date > /home/qiuj5/mytest
