---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
  vars:
    boot_verify_result: true
    boot_proceed: false
  tasks:
  - name: verify centos6 boot files existing
    stat: path: "/boot/{{ centos6_boot_file }}"
    boot_verify_result= centos6_boot_file.stat.exists and boot_verify_result
  - name: record time after run playbook
    shell: date > /home/qiuj5/mytest
    when: boot_count == true
