#working
##python -c 'import crypt; print crypt.crypt("YourPassword", "$6$random_salt")'
---
- name: Update Linux password
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false
  vars:
   userpw: $6$random_salt$jvzwIsVS2aJn.7rBVSpOwXm2JT7WWQD9IO6HmUmKO/UVs8NjF9AON1uLnhrHWkDOqePfJtAhs7rJMbGG4aUZ90
  tasks:
    - name: Update passwd for Linux
      user: name=root update_password=always password={{userpw}}
