---
# tasks file for ./roles/ntt_local_repo
- name: comment out exclude centos-release*,initscripts* in /etc/yum.conf
  lineinfile: dest=/etc/yum.conf line="#exclude=centos-release*,initscripts*" regexp='centos-release' insertbefore=BOF
- name: switch off spacewalk if enabled
  lineinfile: dest=/etc/rhsm/rhsm.conf regexp='^manage_repos' line="manage_repos = 0"
  ignore_errors: yes
- name: stop service gofred & rhsmcertd, if running and disable it
  service: name={{ item }} enabled=no state=stopped
  ignore_errors: yes
  with_items:
  - gofred
  - rhsmcertd
- name: move systemid
  command: mv /etc/sysconfig/rhn/systemid /etc/sysconfig/rhn/systemid.org
  ignore_errors: yes
- name: create /etc/yum.repos.d/old5
#  command: mkdir /etc/yum.repos.d/old2
  file: state=directory path=/etc/yum.repos.d/old5
- name: move repo to /etc/yum.repos.d/old5
  shell: mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/old5
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
- name: get timezone
  shell: ls -la /etc/localtime 2>/dev/null | awk '{print $11}' | awk -F/ '{print $5}'
  register: zone
- name: create NTT local repo for AM production
  template: src=CentOS-Base_localAM.repo dest=/etc/yum.repos.d/CentOS-Base_local.repo
  when: region == 'pln-p'
- name: create NTT local repo for AM non-production
  template: src=CentOS-Base_localAM-nonp.repo dest=/etc/yum.repos.d/CentOS-Base_local.repo
  when: region == 'pln-n'
- name: create NTT local repo for AS production
  template: src=CentOS-Base_localAS.repo dest=/etc/yum.repos.d/CentOS-Base_local.repo
  when: region == 'sin-p'
- name: create NTT local repo for AS non-production
  template: src=CentOS-Base_localAS-nonp.repo dest=/etc/yum.repos.d/CentOS-Base_local.repo
  when: region == 'sin-n'
- name: clean yum repo
  command: yum clean all
