---
  -name: Add members to pool
  bigip_pool_member:
    provider: "{{ provider }}"
    description: "webserver {{ item.name }}"
    host: "{{ item.host }}"
    name: "{{ item.name }}"
    pool: web
    port: 80
  with_items:
    - host: 10.10.10.10
        name: web01
    - host: 10.10.10.20
        name: web02
  delegate_to: localhost
