---
  vars_files:
    - ../vars/vars_boot_file_name.yml
  - name: verify centos6 boot files existing
    stat:
      path: "/boot/{{ item }}"
    register: boot_result
    failed_when: boot_result.stat.exists == false
    with_items: "{{ centos6_boot_file }}"
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
  - name: verify centos7 boot files existing
    stat:
      path: "/boot/{{ item }}"
    register: boot_result
    failed_when: boot_result.stat.exists == false
    with_items: "{{ centos7_boot_file }}"
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
  - name: change record time
    shell: date >> /home/qiuj5/mytest
